### ISSUE TITLE
Required modules

### ISSUE THREAD

**Issue by taufpate** [uhppoted/uhppoted-nodejs#2]
i think that you forgot add "dgram" and "os" as dependencies?

Btw all test give me "ERROR Error: bind EADDRNOTAVAIL 192.168.1.100" (my device is in that ip)

**Comment by uhppoted** [comment]
Hmmm! Interestingly on my machine (\<grin\> yes, I know, but it's still very early stages) it doesn't seem to need them to be declared explicitly. But .. have added `os` to the dependencies anyway.

For `dgram`, _npm_ gives this message:
> npm WARN deprecated dgram@1.0.1: npm is holding this package for security reasons. As it's a core Node module, we will not transfer it over to other users. You may safely remove the package from your dependencies.

On that basis I've left it out for now but if you find you do actually need it declared let me know and I'll add it in. I'll dig into this a bit further - it may be that it was needed for _NodeRED_ but is not actually required for _NodeJS_.

re. _ERROR Error: bind EADDRNOTAVAIL 192.168.1.100_. The bind address should be the IP address of the machine (laptop/desktop/whatever) that is running the _NodeJS_ application. You can generally set it to `0.0.0.0`, but depending on how your network is set up you sometimes need to bind it to the IP address of a specific interface (e.g. it's set to 192.168.1.100 at the moment for my LAN).

If `0.0.0.0`doesn't work and you still have a problem, could you run `ipconfig` (`ifconfig` on _Windows_) and post the output?

**Comment by taufpate** [comment]
with 0.0.0.0 it works perfect!, I thought that was the ip address of the uhppoted device, but I already understood that it really does is a broadcast scan to get the correct device.

Thank you so much! and please, post a link of "buy me a coffee" or similar .. you really deserve donations!

**Comment by uhppoted** [comment]
Ah! Great!!! That's good news! I'll fix the examples so that they aren't dependent on my network setup.

re. broadcast. Yup, the UHPPOTE protocol is essentially designed around UDP broadcast. It's possible to use directed UDP too but requires additional configuration information for each controller so using _broadcast_ is generally simplest.

re. coffee. Awww, thanks :-) :-) .. if the maintenance on this project ever gets out of hand I'll do something like that but for the moment I'm just happy that people are finding it useful.

**Comment by uhppoted** [comment]
Hi,

Quick heads up - have renamed the module name in _package.json_ from `uhppoted-nodejs` to `uhppoted` so you may need to update your imports (apologies!).

And have reworked the examples so that the bind (and broadcast, listen, etc) defaults are more generic and can be set from the command line.

The default values are now:
- `bind`: _0.0.0.0_
- `broadcast`: _255.255.255.255:60000_
- `listen`: _0.0.0.0:60001_
